### PR TITLE
blocklocal now accepts ports in exceptions

### PR DESCRIPTION
**Pull request by oxtoacart**
For getlantern/lantern-internal#1175

### CODE REVIEW

**Comment by merlinran** [comment]
LGTM

**Comment by joesis** [comment]
LGTM

**Comment by atavism** [comment]
I was looking over this too. Just to double check one thing: do we need to add  `127.0.0.1:7300` [here](https://github.com/getlantern/http-proxy/blob/2a0038c793fd06abfe8b994c4c21d2c3bd452377/http_proxy.go#L48) as well?

**Comment by joesis** [comment]
@atavism it's configured in http-proxy-lantern repo.

**Comment by atavism** [comment]
Ok cool, thanks @joesis!

**Pull request merged**
