### PR TITLE
Add logging stuff

### LINKED ISSUE #39: Log to file and rotate
It's vital when deploy the proxy in production.

### PR DESCRIPTION
**Pull request by fffw**
Resolves #39 and #47

### CODE REVIEW

**Comment by fffw** [comment]
Tests in master branch is failing. It would be better to fix them before looking at this PR.

**Comment by uaalto** [comment]
Great @fffw! I see no issue, but I'll give a second pass later, and test it before merging.

**Comment by uaalto** [comment]
Ok, I just read the last comment.

**Comment by fffw** [comment]
Thanks @uaalto!

**Comment by uaalto** [comment]
I'm fixing the tests now.

**Pull request merged**
