### PR TITLE
Switched to using the new proxy package in lieu of interceptor

### PR DESCRIPTION
**Pull request by oxtoacart**
Keeps the back-end code consistent with the Lantern client.

### CODE REVIEW

**Comment by myleshorton** [comment]
Is this one already deployed @oxtoacart?

**Comment by myleshorton** [comment]
@uaalto this would be a good one to take another look at.

**Comment by oxtoacart** [comment]
@myleshorton Yeah, I already deployed a build based on this branch. Would be nice to get it integrated into master before we build again.

**Comment by oxtoacart** [comment]
Just so we don't risk reverting this, I'm merging as it's been live for several weeks and seems to be doing okay.

**Comment by uaalto** [comment]
Now I received the notification, but not before!!! I wasn't aware of this PR, sorry. I would have handled it way sooner. Please ping me on slack if you see no response from me here, some times some Github emails don't land in my inbox...

**Comment by oxtoacart** [comment]
Thanks @uaalto! TBH I didn't want to bother you because you've been very busy dealing with more important issues.

**Pull request merged**
